import { cn } from '@/utils';

import { DayPickerClassNames } from '../CalendarPanel.types';
import { SINGLE_MONTH_WIDTH } from './index';

export const createDayPickerClassNames = (custom?: DayPickerClassNames) => ({
  root: cn('w-fit', custom?.root),
  months: cn('flex', custom?.months),
  month: cn(`flex flex-col w-[${SINGLE_MONTH_WIDTH}px]`, custom?.month),
  month_caption: 'hidden',
  nav: 'hidden',
  day_button: cn(
    'size-[30px]',
    'flex',
    'items-center',
    'justify-center',
    'text-sm',
    'font-semibold',
    'cursor-pointer',
    'rounded-full',
    'hover:bg-slate-100',
    'dark:hover:bg-metal-700',
    'transition-colors',
    'text-[#314158]',
    'dark:text-white',
    'focus:outline-none',
    'focus-visible:outline-none',
    custom?.dayButton,
  ),
  day: cn(
    'p-0',
    'w-[37px]',
    'h-[38px]',
    'text-center',
    'align-middle',
    custom?.day,
  ),
  selected: cn(
    '[&>button]:bg-blue-600',
    '[&>button]:text-white',
    '[&>button]:hover:bg-blue-700',
    'dark:[&>button]:bg-aurora-500',
    'dark:[&>button]:hover:bg-aurora-500',
    'dark:[&>button]:text-metal-900',
    custom?.selected,
  ),
  range_start: cn(
    'drp-range-start',
    '[&>button]:!bg-blue-600',
    '[&>button]:!text-white',
    '[&>button]:!rounded-full',
    '[&>button]:hover:!bg-blue-700',
    '[&>button]:relative',
    '[&>button]:z-10',
    'dark:[&>button]:!bg-aurora-500',
    'dark:[&>button]:hover:!bg-aurora-500',
    'dark:[&>button]:!text-metal-900',
    '!relative',
    'before:absolute',
    'before:top-[4px]',
    'before:bottom-[4px]',
    'before:left-1/2',
    'before:right-0',
    'before:!bg-[#EFF6FF]',
    'dark:before:!bg-aurora-500/10',
    'last:before:!hidden',
    custom?.rangeStart,
  ),
  range_end: cn(
    'drp-range-end',
    '[&>button]:!bg-blue-600',
    '[&>button]:!text-white',
    '[&>button]:!rounded-full',
    '[&>button]:hover:!bg-blue-700',
    '[&>button]:relative',
    '[&>button]:z-10',
    'dark:[&>button]:!bg-aurora-500',
    'dark:[&>button]:hover:!bg-aurora-500',
    'dark:[&>button]:!text-metal-900',
    '!relative',
    'before:absolute',
    'before:top-[4px]',
    'before:bottom-[4px]',
    'before:left-0',
    'before:right-1/2',
    'before:!bg-[#EFF6FF]',
    'dark:before:!bg-aurora-500/10',
    'first:before:!hidden',
    custom?.rangeEnd,
  ),
  range_middle: cn(
    'drp-range-middle',
    '!relative',
    'before:absolute',
    'before:top-[4px]',
    'before:bottom-[4px]',
    'before:left-0',
    'before:right-0',
    'before:!bg-[#EFF6FF]',
    'dark:before:!bg-aurora-500/10',
    'first:before:rounded-l-full',
    'last:before:rounded-r-full',
    '[&>button]:!text-[#314158]',
    '[&>button]:!bg-transparent',
    '[&>button]:!rounded-full',
    '[&>button]:relative',
    '[&>button]:z-10',
    '[&>button]:hover:!bg-blue-100',
    'dark:[&>button]:!text-white',
    'dark:[&>button]:hover:!bg-aurora-500/20',
    custom?.rangeMiddle,
  ),
  table: cn('w-full border-collapse table-fixed', custom?.table),
  weekdays: cn('text-[#62748e]', 'dark:text-metal-400', custom?.weekdays),
  weeks: cn('[&>tr>td]:p-0', '[&>tr]:h-[38px]', custom?.weeks),
  weekday: cn(
    'font-semibold',
    'text-xs',
    'uppercase',
    'text-[#62748e]',
    'dark:text-metal-400',
    'pb-4',
    'w-[37px]',
    custom?.weekday,
  ),
  today: cn(
    '[&>button]:text-[#155dfc]',
    'dark:[&>button]:text-aurora-500',
    custom?.today,
  ),
  month_grid: 'w-full',
  disabled: cn(
    '[&>button]:opacity-50',
    '[&>button]:cursor-not-allowed',
    custom?.disabled,
  ),
  outside: cn(
    '[&>button]:!text-slate-400',
    'dark:[&>button]:!text-metal-500',
    custom?.outside,
  ),
});
