import { cva } from 'class-variance-authority';

export const listGroupLabelVariants = cva([
  'flex',
  'items-center',
  'h-8',
  'px-6',
  'py-1.5',
  'text-[11px]',
  'font-medium',
  'uppercase',
  'tracking-[0.25px]',
  'text-metal-50',
  'pointer-events-none',
  'select-none',
  'cursor-default',
]);

export const listVariants = cva([
  'scrollbar',
  'absolute',
  'bg-white',
  'border',
  'flex-col',
  'mt-1',
  'overflow-hidden',
  'rounded',
  'shadow-2xs',
  'top-full',
  'w-full',
  'z-10',
  'max-h-44',
  'overflow-y-auto',
  'border-gray-200',
  'text-zinc-700',
  'animate-in',
  'fade-in-50',
  'zoom-in-95',
  'duration-200',
  'dark:bg-metal-800',
  'dark:border-metal-700',
  'dark:text-metal-50',
  '[&>li:first-child]:mt-2',
  '[&>li:last-child]:mb-2',
]);
