import { cva } from 'class-variance-authority';

export const listVariants = cva([
  'scrollbar',
  'absolute',
  'bg-white',
  'border',
  'flex-col',
  'mt-1',
  'overflow-hidden',
  'rounded-md',
  'shadow-2xs',
  'top-full',
  'w-full',
  'z-10',
  'max-h-44',
  'overflow-y-auto',
  'border-gray-200',
  'text-zinc-700',
  'animate-in',
  'fade-in-50',
  'zoom-in-95',
  'duration-200',
  'dark:bg-metal-800',
  'dark:border-metal-700',
  'dark:text-metal-50',
  '[&>li:first-child]:mt-2',
  '[&>li:last-child]:mb-2',
]);
