import { cva } from 'class-variance-authority';

export const listVariants = cva([
  'absolute',
  'bg-white',
  'border',
  'flex-col',
  'mt-1',
  'overflow-hidden',
  'rounded-md',
  'shadow-2xs',
  'top-full',
  'w-full',
  'z-10',
  'max-h-[185px]',
  'overflow-y-auto',
  'border-gray-200',
  'text-zinc-700',
  'animate-in',
  'fade-in-50',
  'zoom-in-95',
  'duration-[200ms]',
  'dark:bg-slate-800',
  'dark:border-slate-700',
  'dark:text-slate-50',
]);
