import { cva } from 'class-variance-authority';

export const timePickerVariants = cva([
  'border',
  'rounded',
  'p-2.5',
  'w-full',
  'flex',
  'items-center',
  'justify-between',
  'bg-white',
  'border-gray-300',
  'dark:border-metal-700',
  'dark:bg-metal-800',
  'cursor-pointer',
  'transition-all',
  'transition-duration-100',
  'data-[open=true]:border-aurora-500',
  'text-sm',
  'text-slate-800',
  'dark:text-slate-50',
]);

export const ulVariants = cva([
  'snap-y',
  'snap-mandatory',
  'overflow-y-scroll',
  'scrollbar-none',
  'flex',
  'flex-col',
  'dark:text-metal-50',
]);

export const liVariants = cva([
  'w-15',
  'h-10',
  'snap-start',
  'rounded',
  'transition-all',
  'transition-duration-100',
  'outline-none',
  'border-2',
  'border-transparent',
  'hover:bg-gray-100',
  'focus-within:bg-gray-100',
  'data-[active=true]:bg-blue-600',
  'data-[active=true]:text-white',
  'data-[active=true]:font-medium',
  'data-[active=true]:hover:border-blue-200',
  'data-[active=true]:focus-within:bg-blue-600',
  'data-[active=true]:focus-within:border-blue-200',
  'dark:data-[active=true]:bg-aurora-500',
  'dark:data-[active=true]:text-metal-900',
  'dark:data-[active=true]:hover:border-aurora-50',
  'dark:data-[active=true]:focus-within:bg-aurora-500',
  'dark:data-[active=true]:focus-within:border-aurora-50',
  'dark:hover:bg-metal-700',
  'dark:focus-within:bg-metal-700',
]);

export const buttonVariants = cva([
  'flex',
  'items-center',
  'justify-center',
  'cursor-pointer',
  'w-full',
  'h-full',
  'px-6',
  'py-3',
  'outline-none',
  'text-sm',
]);
