name: Update Changelog

on:
  release:
    types: [published]

jobs:
  generate-changelog:
    runs-on: self-hosted

    permissions:
      contents: write
      actions: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libssl-dev libreadline-dev zlib1g-dev

      - name: Clone ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          sudo ./ruby-build/install.sh

      - name: Install Ruby 3.3
        run: |
          sudo ruby-build 3.3.0 /opt/hostedtoolcache/Ruby/3.3/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.3/x64.complete

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install github-changelog-generator
        run: |
          gem install github_changelog_generator

      - name: Generate Changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          github_changelog_generator --user konstructio --project konstruct-ui

      - name: Extract release version
        id: extract_version
        run: |
          echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config user.name "konstruct-bot"
          git config user.email "konstruct-bot@konstruct.io"
          git fetch origin main
          git checkout main
          git add CHANGELOG.md
          git commit -m "🚀 chore: update changelog for the version ${RELEASE_VERSION}" --no-verify
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Dispatch release
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{
            "event_type": "release",
            "client_payload": {
              "version": "${{ github.event.release.tag_name }}",
              "url": "${{ github.event.release.html_url }}"
            }
          }'
